using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Web2Mail")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Web2Mail")]
[assembly: AssemblyCopyright("kemunpus@hotmail.com")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.1.0.9")]
[assembly: AssemblyFileVersion("1.1.0.9")]
[assembly: ComVisible(false)]
[assembly: System.CLSCompliant(false)]
